version: "3"

services:
  db:
    image: postgres:latest
    container_name: toujours_skateboarding-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toujours_skateboarding
    volumes:
      - toujours_skateboarding-db-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"

volumes:
  toujours_skateboarding-db-data:

